# Generated by Django 4.2.13 on 2024-06-25 07:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PH', verbose_name='Telephone Number')),
                ('mobile_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PH', verbose_name='Mobile Phone Number')),
                ('region', models.CharField(choices=[('I', 'Ilocos Region'), ('II', 'Cagayan Valley'), ('III', 'Central Luzon'), ('IV-A', 'CALABARZON'), ('IV-B', 'MIMAROPA'), ('V', 'Bicol Region'), ('VI', 'Western Visayas'), ('VII', 'Central Visayas'), ('VIII', 'Eastern Visayas'), ('IX', 'Zamboanga Peninsula'), ('X', 'Northern Mindanao'), ('XI', 'Davao Region'), ('XII', 'SOCCSKSARGEN'), ('XIII', 'Caraga'), ('CAR', 'Cordillera Administrative Region'), ('NCR', 'National Capital Region'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
